name: cs5670_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - opencv
  - pillow
  - py-opencv
  - pyparsing
  - python
  - pyttk
  - scipy
  - tk


